name: Create Release

on:
  push:
    tags:
      - "v*" # Triggers on tags like v1.0, v2.3.4

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Build and package release
        run: |
          chmod +x ./release.sh
          ./release.sh

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bunproxy-*.tar.gz
            bunproxy-*-checksums.txt
          body: |
            Release for version ${{ github.ref_name }}

            ## BunProxy

            This release is built with [Bun](https://bun.sh/), a fast JavaScript runtime that provides superior performance compared to Node.js.

            ### Installation

            ```bash
            tar -xzf bunproxy-*.tar.gz
            cd bunproxy-*
            sudo ./install.sh
            ```
          draft: false
          prerelease: false
